### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by kkasberg** [jedediahfrey/PBS_Kids#1]
I am getting the following errors:

```
./pbs_stage1.py
Loading shows from web...
Traceback (most recent call last):
  File "./pbs_stage1.py", line 26, in <module>
    shows_result = json.loads(resp.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Can you tell me what I am doing wrong?

**Comment by frigidplatypus** [comment]
I'm not sure, but I think that PBS has changed something on their end.  I've tried a few different scripts and none are working.
